-- Kisaan sample seed data (public reference tables).
-- Mandi rows are realistic SAMPLE prices in Agmarknet format; replace with a
-- live sync job in production.

INSERT INTO mandi_prices (crop_key, variety, market, district, state, min_price, modal_price, max_price, price_date) VALUES
('wheat','Lokwan','Muzaffarnagar','Muzaffarnagar','Uttar Pradesh',2580,2650,2720,'2026-10-01'),
('wheat','Dara','Khanna','Ludhiana','Punjab',2520,2610,2700,'2026-10-01'),
('wheat','Sharbati','Indore','Indore','Madhya Pradesh',2700,2820,2950,'2026-10-01'),
('paddy','Common','Saharanpur','Saharanpur','Uttar Pradesh',2280,2350,2420,'2026-10-01'),
('paddy','Basmati 1121','Karnal','Karnal','Haryana',3850,4100,4350,'2026-10-01'),
('maize','Yellow','Davangere','Davangere','Karnataka',2100,2200,2300,'2026-10-01'),
('mustard','Black','Bikaner','Bikaner','Rajasthan',5450,5650,5900,'2026-10-01'),
('soybean','Yellow','Indore','Indore','Madhya Pradesh',4350,4550,4780,'2026-10-01'),
('cotton','Medium Staple','Jalna','Jalna','Maharashtra',7100,7400,7700,'2026-10-01'),
('potato','Local','Agra','Agra','Uttar Pradesh',1150,1300,1500,'2026-10-01'),
('onion','Local','Lasalgaon (Niphad)','Nashik','Maharashtra',1300,1600,2100,'2026-10-01'),
('tomato','Local','Kolar','Kolar','Karnataka',900,1250,1700,'2026-10-01'),
('chickpea','Desi','Ujjain','Ujjain','Madhya Pradesh',5250,5450,5700,'2026-10-01'),
('groundnut','Bold','Rajkot','Rajkot','Gujarat',6400,6650,6950,'2026-10-01'),
('arhar','Red','Latur','Latur','Maharashtra',10200,10800,11400,'2026-10-01'),
('moong','Green (Saba)','Etawah','Etawah','Uttar Pradesh',7600,8000,8400,'2026-10-01'),
('sugarcane','Co 0238','Muzaffarnagar','Muzaffarnagar','Uttar Pradesh',340,355,370,'2026-10-01'),
('bajra','Hybrid','Jaipur (Grain)','Jaipur','Rajasthan',2400,2550,2700,'2026-10-01')
ON CONFLICT DO NOTHING;

INSERT INTO schemes
(id, name_en, name_hi, ministry_en, ministry_hi, category,
 summary_en, summary_hi, benefits_en, benefits_hi, eligibility_en, eligibility_hi,
 how_to_apply_en, how_to_apply_hi, documents_en, documents_hi, url, verified_on) VALUES
('pm-kisan','PM-KISAN Samman Nidhi','पीएम-किसान सम्मान निधि',
 'Ministry of Agriculture & Farmers Welfare','कृषि एवं किसान कल्याण मंत्रालय','incomeSupport',
 'Direct income support of ₹6,000 per year to landholding farmer families, paid in three equal instalments.',
 'भूमिधारक किसान परिवारों को ₹6,000 प्रति वर्ष की सीधी आय सहायता, तीन समान किश्तों में।',
 '₹2,000 x 3 instalments per year, transferred directly to bank account (DBT).',
 '₹2,000 x 3 किश्तें प्रति वर्ष, सीधे बैंक खाते में (DBT)।',
 'Landholding farmer families. Certain categories excluded (income-tax payers, institutional landholders, specified government employees).',
 'भूमिधारक किसान परिवार। कुछ श्रेणियां अपवर्जित हैं — आयकर दाता, संस्थागत भूमिधारक, निर्दिष्ट सरकारी कर्मचारी।',
 'Apply at pmkisan.gov.in ("New Farmer Registration"), or via Patwari / Agriculture officer / CSC. e-KYC mandatory.',
 'pmkisan.gov.in ("नया किसान पंजीकरण") पर आवेदन करें, या पटवारी / कृषि अधिकारी / सीएससी से। e-KYC अनिवार्य।',
 'Aadhaar, land ownership records, bank account passbook, mobile number.',
 'आधार, भूमि स्वामित्व रिकॉर्ड, बैंक पासबुक, मोबाइल नंबर।',
 'https://pmkisan.gov.in','2026-09-15'),
('pmfby','Pradhan Mantri Fasal Bima Yojana (PMFBY)','प्रधानमंत्री फसल बीमा योजना',
 'Ministry of Agriculture & Farmers Welfare','कृषि एवं किसान कल्याण मंत्रालय','insurance',
 'Crop insurance against yield losses from natural calamities, pests and diseases, at very low farmer premium.',
 'प्राकृतिक आपदा, कीटों और रोगों से उपज हानि के विरुद्ध फसल बीमा, बहुत कम प्रीमियम पर।',
 'Farmer pays only 2% (Kharif food/oilseed), 1.5% (Rabi food/oilseed), 5% (commercial/horticultural). Claims via DBT.',
 'किसान केवल 2% (खरीफ), 1.5% (रबी), 5% (व्यावसायिक/बागवानी) प्रीमियम देता है। दावा DBT से।',
 'All farmers growing notified crops in notified areas, including sharecroppers and tenant farmers.',
 'सूचित क्षेत्रों में सूचित फसलें उगाने वाले सभी किसान, बटाईदार व किरायेदार सहित।',
 'Enrol through bank/CSC before the state cutoff each season, or on pmfby.gov.in.',
 'हर मौसम की राज्य अंतिम तिथि से पहले बैंक/सीएससी से, या pmfby.gov.in पर पंजीकरण करें।',
 'Aadhaar, bank account, land records, sowing certificate for tenants.',
 'आधार, बैंक खाता, भूमि रिकॉर्ड, किरायेदारों हेतु बुवाई प्रमाणपत्र।',
 'https://pmfby.gov.in','2026-09-15'),
('kcc','Kisan Credit Card (KCC)','किसान क्रेडिट कार्ड (KCC)',
 'Ministry of Finance / NABARD','वित्त मंत्रालय / नाबार्ड','credit',
 'Short-term credit for cultivation at concessional interest, with RuPay debit card facility.',
 'रियायती ब्याज पर खेती के लिए अल्पकालिक ऋण, RuPay डेबिट कार्ड सहित।',
 'Crop loans up to ₹3 lakh at effective 4% p.a. (with incentives/subvention). Covers cultivation, post-harvest, farm assets.',
 '₹3 लाख तक फसल ऋण, प्रभावी 4% वार्षिक ब्याज पर। खेती, कटाई-पश्चात व कृषि संपत्ति शामिल।',
 'All farmers — owner cultivators, tenants, oral lessees, sharecroppers, SHG/JLG members.',
 'सभी किसान — स्वामी कृषक, किरायेदार, मौखिक पट्टेदार, बटाईदार, समूह सदस्य।',
 'Apply at nearest bank branch or bank portal / pmkisan.gov.in KCC link. Valid 5 years.',
 'निकटतम बैंक शाखा या बैंक पोर्टल / pmkisan.gov.in KCC लिंक से आवेदन। 5 वर्ष वैध।',
 'Aadhaar, PAN, land records, passport photo.',
 'आधार, पैन, भूमि रिकॉर्ड, पासपोर्ट फोटो।',
 'https://www.mudraka.com/kisan-credit-card','2026-09-15'),
('pm-kusum','PM-KUSUM (Solar Pumps)','पीएम-कुसुम (सोलर पंप)',
 'Ministry of New & Renewable Energy','नवीन और नवीकरणीय ऊर्जा मंत्रालय','irrigation',
 'Subsidised standalone solar pumps, solarisation of grid pumps, and income from surplus solar power.',
 'रियायती सौर पंप, ग्रिड पंपों का सौरीकरण, अतिरिक्त सौर बिजली से आय।',
 'Up to 60% subsidy on standalone solar pumps; extra income by selling surplus power to DISCOMs.',
 'स्टैंडअलोन सौर पंपों पर 60% तक सब्सिडी; अतिरिक्त बिजली बेचकर अतिरिक्त आय।',
 'Individual farmers, FPOs, water user associations, cooperatives.',
 'व्यक्तिगत किसान, एफपीओ, जल उपयोगकर्ता संघ, सहकारी समितियां।',
 'Apply on State Nodal Agency portal when open (links on pmkusum.mnre.gov.in).',
 'राज्य नोडल एजेंसी पोर्टल पर आवेदन करें (लिंक pmkusum.mnre.gov.in पर)।',
 'Aadhaar, land records, bank account, electricity connection details.',
 'आधार, भूमि रिकॉर्ड, बैंक खाता, बिजली कनेक्शन विवरण।',
 'https://pmkusum.mnre.gov.in','2026-09-15'),
('soil-health-card','Soil Health Card Scheme','मृदा स्वास्थ्य कार्ड योजना',
 'Ministry of Agriculture & Farmers Welfare','कृषि एवं किसान कल्याण मंत्रालय','organic',
 'Free soil testing with a card giving crop-wise fertiliser and nutrient recommendations.',
 'मुफ्त मिट्टी परीक्षण और फसलवार उर्वरक सिफारिशों वाला कार्ड।',
 'Soil tested for N,P,K,S,micro-nutrients,pH,EC; card suggests fertiliser doses per crop.',
 'मिट्टी में N,P,K,S,सूक्ष्म पोषक,pH,EC की जांच; कार्ड प्रति फसल उर्वरक मात्रा बताता है।',
 'All farmers holding agricultural land.',
 'कृषि भूमि धारण करने वाले सभी किसान।',
 'Contact block Agriculture office or KVK; cards free, refreshed every 2-3 years.',
 'ब्लॉक कृषि कार्यालय या KVK से संपर्क करें; कार्ड निःशुल्क, हर 2-3 वर्ष नवीनीकृत।',
 'Aadhaar, land records, mobile number.',
 'आधार, भूमि रिकॉर्ड, मोबाइल नंबर।',
 'https://soilhealth.dac.gov.in','2026-09-15'),
('kishan-maandhan','PM Kisan Maandhan Yojana','पीएम किसान मानधन योजना',
 'Ministry of Agriculture & Farmers Welfare','कृषि एवं किसान कल्याण मंत्रालय','pension',
 'Monthly pension of ₹3,000 for small and marginal farmers after age 60.',
 '60 वर्ष बाद छोटे व सीमांत किसानों को ₹3,000 मासिक पेंशन।',
 'Guaranteed ₹3,000/month from age 60; farmer contributes ₹55–₹200/month, Government matches. 50% family pension.',
 '60 वर्ष से ₹3,000/माह गारंटीकृत; किसान ₹55–₹200/माह योगदान, सरकार समान योगदान। 50% पारिवारिक पेंशन।',
 'Small & marginal farmers (up to 2 ha), age 18–40, not covered by other statutory schemes.',
 'छोटे व सीमांत किसान (2 हेक्टेयर तक), आयु 18–40, अन्य वैधानिक योजनाओं से अनाच्छादित।',
 'Enrol at a Common Service Centre (CSC) or maandhan.in.',
 'सीएससी पर या maandhan.in पर पंजीकरण करें।',
 'Aadhaar, land records, savings bank account or KCC.',
 'आधार, भूमि रिकॉर्ड, बचत बैंक खाता या KCC।',
 'https://maandhan.in','2026-09-15')
ON CONFLICT (id) DO NOTHING;
